name: "tagged-release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Get Latest Tag
      id: get-latest-tag
      run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

    - uses: actions-ecosystem/action-bump-semver@v1
      id: bump-semver
      with:
        current_version: ${{ steps.get-latest-tag.outputs.tag }}
        level: minor
        
    - uses: madhead/semver-utils@latest
      id: version
      with:
        # A version to work with
        version: ${{ steps.bump-semver.outputs.new_version }}

    - name: Prep Tag
      env:
        latest_version: ${{ steps.bump-semver.outputs.new_version }}
        latest_version_num: "${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}.${{ steps.version.outputs.build }}"
      run: echo $env:latest_version_num 
           echo $env:latest_version
        
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -p:Version=$env:latest_version_num -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Zip Release
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
      uses: TheDoctor0/zip-release@0.6.2
      with:
        # Filename for archive
        filename: WinBGMuter.zip
        # Base path for archive files
        path: . # optional, default is .
        # Working directory before zipping
        directory: .\WinBGMute\bin\publish\WinBGMuter # optional, default is .
        # List of excluded files / directories
        exclusions: WinBGMuter.pdb # optional, default is 
        # Tool to use for archiving
        type: zip # optional, default is zip
    - name: Test
      run: file WinBGMuter.zip
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "$env:latest_version"
        prerelease: true
        title: "$env:latest_version"
        files: |
          WinBGMuter.zip

